url: "https://anthonysterling.com"
permalink: "/posts/:title.html"
timezone: "Europe/London"
encoding: "utf-8"
paginate: 10
paginate_path: "/posts/:num"
exclude: ["Makefile", "CNAME"]
gems: ["jekyll-paginate"]
highlighter: rouge
